### ISSUE TITLE
XDMF output broken for parallel runs

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#45] opened 2023-05-22 16:51 UTC
The VisIt cannot load the XDMF output written out for a parallel run.

```
cd build/driver/tests/swe_roe
/opt/local/bin/mpiexec-openmpi-mp -n 2 ../../rdycore ex2b.yaml
```

I noticed that the vertices in `/geometry/vertices` between a serial and parallel run differ.  The `/viz/topology/cells` are also different. We should be writing out `/geometry/vertices` and `/viz/topology/cells` that are the same for serial and parallel runs. We probably need to tell DMPlex to save natural vertex ids before distributing the DMPlex. Additionally, we may need to add 1 fake DOFs on vertices.

**Comment by jeff-cohere** [comment] 2023-05-22 17:09
I can confirm that `/geometry/vertices` and `/viz/topology/cells` do indeed differ between serial and parallel runs.

**Comment by jeff-cohere** [comment] 2023-05-22 17:50
@knepley , does data written by the XDMF viewer via `DMView` write out grid topology/geometry data in natural order if `DMSetUseNatural` has been called with `PETSC_TRUE`?

**Comment by knepley** [comment] 2023-05-22 18:04
No, but we can probably add that. We have been focused on checkpointing, which is agnostic to the order.

**Comment by jeff-cohere** [comment] 2023-05-22 18:09
If it's a reasonable thing to expect for `DMView` to respect `DMSetUseNatural`, that would be great!

**Comment by jeff-cohere** [comment] 2023-12-18 16:19
@knepley , here's the issue we've been using to track the XDMF output behavior.

**Comment by knepley** [comment] 2023-12-18 16:31
In the email thread, I suggested using `VecGetSize()` on the coordinate vector and dividing by the spatial dimension.

**Comment by jeff-cohere** [comment] 2024-02-21 16:15
I'm closing this issue, since I believe it's been addressed properly now.

**Closed by jeff-cohere** 2024-02-21 16:15 UTC
Labels: petsc, I/O
